# Generated by Django 4.1.7 on 2023-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_maplocation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='place_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
